### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by Shiro-LK** [StopPropagHate/experiment_evalita_HaSpeeDe#1]
Hi,

I was interesting by your study and I was wondering how can I get the data you used in order to do the experiments ? I haven't found any links

**Comment by paulafortuna** [comment]
Hi,

Here you can find the link for the report where this shared tasks are presented:
http://personales.upv.es/prosso/resources/FersiniEtAl_Evalita18.pdf

You can see if in this papers there are links for the datasets, or consider contacting the authors in case not.
Another valuable tool compiling hate speech related resources it is presented here:
https://github.com/aymeam/Datasets-for-Hate-Speech-Detection
